/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apk_Penyewaan_PC;

import javax.swing.JOptionPane;

/**
 *
 * @author myusu
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnoperator2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        btncustomer = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btncashier = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        operator = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        customer = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        cashier = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        lapOperator = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        lapcustomer = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        lapTransaksi = new javax.swing.JMenuItem();
        Keluar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("JASA SEWA PC WARNET");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(194, 194, 194)
                    .addComponent(jLabel8)
                    .addContainerGap(195, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(199, 199, 199)
                    .addComponent(jLabel8)
                    .addContainerGap(200, Short.MAX_VALUE)))
        );

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        btnoperator2.setIcon(new javax.swing.ImageIcon("D:\\SEMESTER 5\\PBO 2\\UAS\\M.Yusuf_19630360_TB\\icons\\icons8-operator-64.png")); // NOI18N
        btnoperator2.setText("OPERATOR");
        btnoperator2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoperator2ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnoperator2);
        jToolBar1.add(jSeparator1);
        jToolBar1.add(jSeparator6);

        btncustomer.setIcon(new javax.swing.ImageIcon("D:\\SEMESTER 5\\PBO 2\\UAS\\M.Yusuf_19630360_TB\\icons\\icons8-circled-user-male-skin-type-7-48.png")); // NOI18N
        btncustomer.setText("COSTOMER");
        btncustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncustomerActionPerformed(evt);
            }
        });
        jToolBar1.add(btncustomer);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator7);

        btncashier.setIcon(new javax.swing.ImageIcon("D:\\SEMESTER 5\\PBO 2\\UAS\\M.Yusuf_19630360_TB\\icons\\clerk.png")); // NOI18N
        btncashier.setText("CASHIER");
        btncashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncashierActionPerformed(evt);
            }
        });
        jToolBar1.add(btncashier);

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 0));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenu2.setText("Home");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Menu");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        operator.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        operator.setText("operator");
        operator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                operatorActionPerformed(evt);
            }
        });
        jMenu3.add(operator);
        jMenu3.add(jSeparator3);

        customer.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        customer.setText("customer");
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        jMenu3.add(customer);
        jMenu3.add(jSeparator5);

        cashier.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cashier.setText("cashier");
        cashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashierActionPerformed(evt);
            }
        });
        jMenu3.add(cashier);

        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(255, 204, 0));
        jMenu4.setText("Laporan");
        jMenu4.setFocusCycleRoot(true);
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N

        lapOperator.setText("Laporan Data Operator");
        lapOperator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapOperatorActionPerformed(evt);
            }
        });
        jMenu4.add(lapOperator);
        jMenu4.add(jSeparator8);

        lapcustomer.setText("Laporan Data Customer");
        lapcustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapcustomerActionPerformed(evt);
            }
        });
        jMenu4.add(lapcustomer);
        jMenu4.add(jSeparator9);

        lapTransaksi.setText("Laporan Data Transaksi");
        lapTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lapTransaksiActionPerformed(evt);
            }
        });
        jMenu4.add(lapTransaksi);

        jMenuBar1.add(jMenu4);

        Keluar.setText("Keluar");
        Keluar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Keluar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        Keluar.add(jMenuItem1);

        jMenuBar1.add(Keluar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btncustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncustomerActionPerformed
        // TODO add your handling code here:
        new FormPelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncustomerActionPerformed

    private void btnoperator2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoperator2ActionPerformed
        // TODO add your handling code here:
        new FormOperator().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnoperator2ActionPerformed

    private void operatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_operatorActionPerformed
        // TODO add your handling code here:
        new FormOperator().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_operatorActionPerformed

    private void cashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashierActionPerformed
        // TODO add your handling code here
        new FormTransaksi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cashierActionPerformed

    private void btncashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncashierActionPerformed
        // TODO add your handling code here
        new FormTransaksi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncashierActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
        // TODO add your handling code here:
        new FormPelanggan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerActionPerformed

    private void lapOperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapOperatorActionPerformed
        // TODO add your handling code here:
        new ConfigDB().reportData("Operator", "operator", "operator");
    }//GEN-LAST:event_lapOperatorActionPerformed

    private void lapTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapTransaksiActionPerformed
        // TODO add your handling code here
       String SQL = "select pelanggan.id_pelanggan, transaksi.kd_transaksi, pelanggan.nama, pelanggan.durasi, transaksi.tgl_transaksi, transaksi.status FROM transaksi INNER JOIN pelanggan ON transaksi.id_pelanggan = pelanggan.id_pelanggan";

        new ConfigDB().ReportShow("src/Laporan_transaksi/report_transaksi.jrxml", SQL);
    }//GEN-LAST:event_lapTransaksiActionPerformed

    private void lapcustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lapcustomerActionPerformed
        // TODO add your handling code here
        new ConfigDB().reportData("Pelanggan", "pelanggan", "pelanggan");
    }//GEN-LAST:event_lapcustomerActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new FormLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Keluar;
    private javax.swing.JButton btncashier;
    private javax.swing.JButton btncustomer;
    private javax.swing.JButton btnoperator2;
    private javax.swing.JMenuItem cashier;
    private javax.swing.JMenuItem customer;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem lapOperator;
    private javax.swing.JMenuItem lapTransaksi;
    private javax.swing.JMenuItem lapcustomer;
    private javax.swing.JMenuItem operator;
    // End of variables declaration//GEN-END:variables
}
