/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Apk_Penyewaan_PC;

/**
 *
 * @author myusu
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JMenuBar();
        Home = new javax.swing.JMenu();
        FormMenu = new javax.swing.JMenu();
        Operator = new javax.swing.JMenuItem();
        Anggota = new javax.swing.JMenuItem();
        Profil = new javax.swing.JMenu();
        Exit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 839, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        Menu.setBackground(new java.awt.Color(51, 0, 255));
        Menu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Menu.setMargin(new java.awt.Insets(0, 0, 10, 0));

        Home.setBackground(new java.awt.Color(0, 102, 255));
        Home.setForeground(new java.awt.Color(0, 204, 204));
        Home.setText("Home");
        Home.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Menu.add(Home);

        FormMenu.setForeground(new java.awt.Color(255, 0, 153));
        FormMenu.setText("Form Menu");
        FormMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FormMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FormMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Operator.setText("Operator");
        Operator.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OperatorMouseClicked(evt);
            }
        });
        Operator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperatorActionPerformed(evt);
            }
        });
        FormMenu.add(Operator);

        Anggota.setText("Anggota");
        Anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnggotaActionPerformed(evt);
            }
        });
        FormMenu.add(Anggota);

        Menu.add(FormMenu);

        Profil.setForeground(new java.awt.Color(204, 0, 204));
        Profil.setText("Profil");
        Profil.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Menu.add(Profil);

        Exit.setText("Exit");
        Menu.add(Exit);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 434, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperatorActionPerformed
        // TODO add your handling code here:
        new Operator().setVisible(true);
    }//GEN-LAST:event_OperatorActionPerformed

    private void OperatorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OperatorMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_OperatorMouseClicked

    private void AnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnggotaActionPerformed
        // TODO add your handling code here:
        new Pelanggan().setVisible(true);
    }//GEN-LAST:event_AnggotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Anggota;
    private javax.swing.JMenu Exit;
    private javax.swing.JMenu FormMenu;
    private javax.swing.JMenu Home;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem Operator;
    private javax.swing.JMenu Profil;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
